version: 2
jobs:
  decent:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Decent Group"
          command: echo "Build, Away!"
      - run: ./circleci-diag.sh
workflows:
  decent-workflow:
    jobs:
      - decent