version: 2.1

jobs:
  decent:

    docker:
      - image: ruby:2.5

    steps:
      - checkout
      - run:
          name: "Decent Team"
          command: "echo Build, Away!"
      - run: ./circleci-diag.sh

workflows:
  decent-workflow:
    jobs:
      - decent
