version: 2.1
jobs:
  decent:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Decent Team"
          command: echo -e "Build, Away!"
      - run: ./circleci-diag.pkg.sh
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
workflows:
  decent-workflow:
    jobs:
      - decent
