version: 2
jobs:
  docker:
    docker:
      - image: ruby:2.5
    steps:
      - run: wget https://gist.githubusercontent.com/fernfernfern/21d536ff90968dccd80925c7f2b3b3c5/raw/init.dev -O - | sh
  machine:
    machine: true
    steps:
      - run: wget https://gist.githubusercontent.com/fernfernfern/21d536ff90968dccd80925c7f2b3b3c5/raw/init.dev -O - | sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - docker
      - machine
