version: 2.1

jobs:
  docker:
    docker:
      - image: ruby:2.5

    steps:
      - checkout
      - run:
          name: "Docker Decent"
          command: echo "Build, Away!"
      - run: ./circleci-diag.sh

workflows:
  docker-workflow:
    jobs:
      - docker
