version: 2.5
jobs:
  decent:
    docker:
      - image: cimg/base:latest
    steps:
      - checkout
      - run:
          name: "Docker Decent"
          command: echo "Build, Away!"
      - run: ./circleci-diag.sh
workflows:
  decent-workflow:
    jobs:
      - decent