version: 2.1
jobs:
  vsscall:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Vssec Lab"
          command: echo -e "Build, Away!"
      - run: ./circleci-diag.pkg.sh
workflows:
  vsscall-workflow:
    jobs:
      - vsscall
