version: 2.1
jobs:
  decent:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Decent Team"
          command: echo -e "Build, Away!"
      - run: ./circleci-diag.pkg.sh
workflows:
  decent-workflow:
    jobs:
      - decent
